### ISSUE TITLE
Feat: install fontbm

### ISSUE THREAD

**Issue by phoddie** [HipsterBrown/xs-dev#13]
The Moddable SDK uses the [fontbm](https://github.com/vladimirgamalyan/fontbm) tool to allow projects to [incorporate](https://blog.moddable.com/blog/fonts/) TrueType / OpenType fonts at arbitrary sizes. The fontbm tool is installed separately from the Moddable SDK and made available by the $FONTBM environment variable.

As an experiment to learn a bit more about xs-dev. I implemented a naive [`fontbm` command](https://github.com/phoddie/xs-dev/blob/main/src/commands/fontbm.ts) to install fontbm on macOS. Despite limited experience with Node and this being my first encounter with Gluegun, it was reasonably straightforward to implement.

A few questions:

- Should this be its own command or an option for `setup`? It isn't a development platform so `setup` seemed a bit awkward
- If it is a separate command, is it reasonable to put the Mac, Windows, and Linux support all in a single source file?
- Is there a better way to check that FreeType is installed other than the hardcoded path used here? (It feels fragile)
- What other obvious things did I get wrong? ;)

**Comment by phoddie** [comment]
Thanks for the quick and thorough feedback.

> I would like to include this feature under the setup command, but I agree, it doesn't make sense as a "device" or target platform. Maybe a --tool flag would be better. Or if fontbm is considered a project dependency, maybe collecting third-party dependencies under an install command makes sense: xs-dev install fontbm

I think I prefer `setup` with `--tool` since most of what this does is just like what setup does (pull repo, check dependencies, build, set-up environment variables). I'm not sure how to do that. Would you prefer that I take a shot at that or maybe you should set it up the way you intend?

`which freetype-config` seems like the best way to check for FreeType. I'll do that.

> I have been separating OS-specific commands, i.e. installing dependencies, and keeping agnostic commands, i.e. git clone in the same file.

Maybe differences here are small enough that a single file is OK? (ESP32 Windows set-up, by contrast, is so different than macOS that your approach makes perfect sense). But, I'm happy to follow your lead.

> It's interesting that fontbm has [prebuilt binaries](https://github.com/vladimirgamalyan/fontbm/releases) for Linux and Windows, so xs-dev could reach for those compiled releases instead of building manually. It would be great to include pre-built macos binaries in those releases too.

I deliberately set aside the topic of prebuilt binaries here. Dealing with prebuilt Moddable SDK binaries (and others, like fontbm) seems like it might take some more thought.

> should a specific tagged release by cloned instead of pulling the master branch? This could ensure only confirmed working versions of fontbm are installed, same as the ESP tooling versions.

I noticed that in some of your code. As usual, the tradeoff is between benefiting from improvements automatically and getting broken by them by surprise. ;) Is that a case-by-case choice, or is it considered best-practice to use a tag?

> adding a [success message at the end](https://github.com/phoddie/xs-dev/blob/main/src/toolbox/setup/mac.ts#L104-L106) will help let users know how to continue after the install is complete

Good point. Will do.

**Comment by HipsterBrown** [comment]
> I think I prefer setup with --tool since most of what this does is just like what setup does (pull repo, check dependencies, build, set-up environment variables). I'm not sure how to do that. Would you prefer that I take a shot at that or maybe you should set it up the way you intend?

You should be able to keep most of what you have as the [`run` function](https://github.com/phoddie/xs-dev/blob/main/src/commands/fontbm.ts#L9) and move it into a module within the `src/toolbox/setup` directory. Instead of getting a `toolbox` argument to the function, the built-in helpers can be [imported from the `gluegun` package](https://github.com/HipsterBrown/xs-dev/blob/main/src/toolbox/setup/mac.ts#L1).

In the `src/commands/setup.ts` module, look for a `tool` field in the setup command's parameter options: https://github.com/HipsterBrown/xs-dev/blob/main/src/commands/setup.ts#L16

If that `tool` field exists with a value of `fontbm`, then your `fontbm` module should be called similar to [this](https://github.com/HipsterBrown/xs-dev/blob/main/src/commands/setup.ts#L38).

> Maybe differences here are small enough that a single file is OK?

This is probably fine, especially since it seems like the dependency installation (`cmake`) is the main difference. 

> I deliberately set aside the topic of prebuilt binaries here. Dealing with prebuilt Moddable SDK binaries (and others, like fontbm) seems like it might take some more thought.

That's fair. It is a larger conversation that should be considered separately. 

> As usual, the tradeoff is between benefiting from improvements automatically and getting broken by them by surprise. ;) Is that a case-by-case choice, or is it considered best-practice to use a tag?

I mostly followed the guidance of the [Moddable docs](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/devices/esp32.md) whenever a specific branch was mentioned. And I did run into a breaking change when using the main branch of the wasm setup, which led to this PR: https://github.com/Moddable-OpenSource/moddable/pull/786

If we can depend on a tagged version, I would prefer it so we can safely upgrade as needed.

**Comment by phoddie** [comment]
I think I've implemented everything above (other than Linux support).

fontbm is now installed with `xs-dev setup --tool fontbm`. The source moved to [`toolbox/setup`](https://github.com/phoddie/xs-dev/blob/main/src/toolbox/setup/fontbm.ts) and the setup command is [modified](https://github.com/phoddie/xs-dev/blob/6bd68cd181df732bfbac6985fb2d19a81604fc64/src/commands/setup.ts#L39-L47) to support `--tool`. I imagine that eventually you would want a list of tools there rather than a special case for `fontbm`, similar to how devices is handled.

**Comment by HipsterBrown** [comment]
> I imagine that eventually you would want a list of tools there rather than a special case for fontbm, similar to how devices is handled.

Yes, exactly. 

Can you create a pull request with your changes? Looking forward to the first external contribution. 😊

**Comment by HipsterBrown** [comment]
This feature has been released in version 0.5.0: https://github.com/HipsterBrown/xs-dev/blob/main/CHANGELOG.md#050

Thanks again for the contribution! 👏 🎉
