### ISSUE TITLE
feat: streamline setup / update with prebuilt tooling

### ISSUE THREAD

**Issue by HipsterBrown** [HipsterBrown/xs-dev#24]
I've started experimenting with pre-building the Moddable tooling for macos and linux (both x86_64) using GitHub Actions: https://github.com/HipsterBrown/moddable-prebuild

I manually kick off this action whenever I noticed new features within the Moddable repo, which leads to a gzip, tarball release for each platform under the `latest` tag that matches the commit from Moddable. This process could eventually be triggered by a regular cron job that watches for new commits. 

Using these prebuilt releases could speed up the initial setup and future updates for each platform, since the build step would be skipped, especially on resource-lite machines.

Caveats:
I'm currently manually building the macos arm64 releases locally and adding them to the tagged release, so the cron job optimization would not be reliable until GitHub Actions supports arm64 environments or the build process updated to use a custom runner with support for more platforms (including Windows).

**Comment by phoddie** [comment]
Building the tools and having a current set of binaries available for download is one (important!) part of this feature. Another is getting the build to use the binaries. I'm not sure how straightforward that is.

The tools are available because they have been added to the $PATH.

```console
export PATH="/Users/XYZ/.local/share/moddable/build/bin/mac/release:$PATH"
```

That allows developers to run `mcconfig` and `mcrun` directly from the command line.

The build itself doesn't depend on $PATH. For example, [make.esp.mk](https://github.com/Moddable-OpenSource/moddable/blob/public/tools/mcconfig/make.esp.mk) does this:

```mk
ifeq ($(HOST_OS),Darwin)
MODDABLE_TOOLS_DIR = $(BUILD_DIR)/bin/mac/release
else
MODDABLE_TOOLS_DIR = $(BUILD_DIR)/bin/lin/release
endif
```

Maybe it is enough to make those `?=` to allow the tools directory to come from the environment.

Then, xs-dev `install` would need to setup `MODDABLE_TOOLS_DIR` to point to a directory xs-dev manages, use that directory in $PATH, and download the tools binary that matches the currently installed Moddable SDK. xs-dev `update` would need to update those. If either `install` or `update` couldn't find the binaries, then it could still build them as it does today.

FWIW – I would like to see an option to have xs-dev not use the prebuilt binaries, even when available. There are good reasons for that. One is security -- not having to rely on someone else's tool build. Another is to be able to use the install of $MODDABLE by xs-dev to develop / debug the tools.

**Comment by HipsterBrown** [comment]
> Another is getting the build to use the binaries. I'm not sure how straightforward that is.

The current releases in [moddable-prebuild](https://github.com/HipsterBrown/moddable-prebuild) are actually gzipped tarballs of the Moddable repo with the binaries in the expected place. So the most straightforward way of using them would be to download the release for the target OS, untar-zip it in the `~/.local/share/` directory to keep the rest of the environment setting the same. This also keeps the moddable git history in the release, which means it _should_ be update-able through the same `git pull` as expected. 

> FWIW – I would like to see an option to have xs-dev not use the prebuilt binaries, even when available. 

When introducing this, it would be opt-in until we can confirm it is worth it. In the stable (1.0) release, it might be the default workflow with the option to opt-out (`--force-build` or something similar).

**Comment by phoddie** [comment]
Interesting. I've had it in my mind that the binaries should be distributed separately from the sources. I hadn't considered bundling them together. Doing that solves several problems, and should be even faster. 

I have no sense of what's usual here. How common is it to bundle binary and source into a release like that? I guess I'm looking for best practices to guide this.

Wouldn't this approach makes `update` more destructive? If `update` downloads the latest and replaces the current sources, any changes in the repository would be lost. Maybe if you are operating at that level, it is a signal you should be building tools too...

**Comment by HipsterBrown** [comment]
> I have no sense of what's usual here. How common is it to bundle binary and source into a release like that? I guess I'm looking for best practices to guide this.

I don't know what's typical either. The fact that the binaries and SDK are included in the single repo lead me to keep this approach until the two are split in some way. If the tooling (CLIs, simulators, debugger) was a separate repo, it would be easier to ship the binaries without the source. But most projects will reference SDK code in the Moddable repo, so may as well include it all in pre-built releases. 

> Wouldn't this approach makes update more destructive? If update downloads the latest and replaces the current sources, any changes in the repository would be lost. Maybe if you are operating at that level, it is a signal you should be building tools too...

Yes, this is true on both points. My experience is treating the Moddable repo as a dependency of my embedded project, rather than a workspace for it. I should be able to teardown and setup my environment without impacting my projects that depend on the SDK. If the project relies on a fork of the SDK or local changes, then the safer update would mean opting out of the pre-built releases and using the stash+pull+build workflow.

**Comment by phoddie** [comment]
> I don't know what's typical either

Cool. So we are really learning.

> The fact that the binaries and SDK are included in the single repo lead me to keep this approach until the two are split in some way. If the tooling (CLIs, simulators, debugger) was a separate repo

That could be a long wait. ;) Some of the tools use parts of the SDK (for example, xsbug and the simulator both use Piu) and they all use XS in one way or another. It is very convenient that those are bundled together because it ensures they are updated together. There would need to be a big win to do the work to separate those and then live with the added complexity moving forward. My sense is that we can find a solution for delivering binaries that doesn't require it.

> My experience is treating the Moddable repo as a dependency of my embedded project, rather than a workspace for it. 

I understand. It is a dependency, just not in the same way as a module. I'd hesitate to use the common idea of a project dependency here.

It sounds like are storing your project code outside the SDK. That makes sense. We do the same for our commercial work and experimental modules. You are probably still storing build results (`tmp` and `bin` directories) in the Moddable SDK directory. Those can be external too (`$BUILD_DIR`) which is useful for keeping the SDK repository entirely unchanged.

> If the project relies on a fork of the SDK or local changes, then the safer update would mean opting out of the pre-built releases and using the stash+pull+build workflow.

If we by-pass git to retrieve the SDK, agreed. I'm concerned developers may only learn that the hard way. It is pretty natural to jump in and start editing files to solve a problem. 

To be 1000% clear, I'm not advocating for a solution. I genuinely don't know. I need to think about this some more.

**Comment by dashcraft** [comment]
Just my 2 sense here, the easiest thing might be to consider moddable similar to a runtime for installation, create a manager similar to NVM, that can download, point to and install moddable binaries on your local machine. Then, is XS dev, you could essentially have a reconciliation process similar to package.json engine, or .ruby-version etc that checks to see if the correct local version of moddable is available through the tool/cli interface.

Here are some potential upsides:
1. You only need to add the environment manager once to the shell script, internally it'd keep track of which versions are present
2. It allows for users to self configure each projects version and incrementally upgrade projects over time
3. It would allows users to also install upstream binaries directly from git (similar to nvm) in case they want to use a version that isn't updated in the cli's `list` command

Some potential downsides:
1. It's an entirely separate package, double the complexity for what you're doing in xs-dev
2. Not sure if there are any residual changes leftover between runs in different moddable versions
3. Lots of potential for Bloating someone's local file system with a bunch of versions
4. Managing installation locations between each OS

https://github.com/nvm-sh/nvm
